### ISSUE TITLE
Breaks with Rails 4.1's Spring, doesn't instafail with Rspec 3.0.0.beta2

### ISSUE THREAD

**Issue by paulkoegel** [grosser/rspec-instafail#16]
i'm running `rspec-core (3.0.0.beta2)` via `rspec-rails (3.0.0.beta2)` in Rails 4.1.0.rc1.
When I run `rspec spec` specs don't throw an error, but everything happens as if instafail wasn't running - no instant display of failing specs' details.
With Spring (`bin/rspec spec`) I get the following error:

```
bin/rspec spec/controllers
/Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_formatter.rb:17:in `<class:BaseFormatter>': undefined method `register' for RSpec::Core::Formatters:Module (NoMethodError)
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_formatter.rb:14:in `<module:Formatters>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_formatter.rb:6:in `<module:Core>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_formatter.rb:5:in `<module:RSpec>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_formatter.rb:4:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/base_text_formatter.rb:1:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.0.0.beta2/lib/rspec/core/formatters/progress_formatter.rb:1:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-instafail-0.2.4/lib/rspec/instafail/rspec_2.rb:1:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:247:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-instafail-0.2.4/lib/rspec/instafail.rb:8:in `<module:RSpec>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-instafail-0.2.4/lib/rspec/instafail.rb:1:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:85:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:85:in `rescue in block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:68:in `block in require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `each'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler.rb:131:in `require'
from /Users/paul/blitzbude/repo/config/application.rb:8:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:82:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:82:in `preload'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:140:in `serve'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:128:in `block in run'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:122:in `loop'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application.rb:122:in `run'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/spring-1.1.2/lib/spring/application/boot.rb:18:in `<top (required)>'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/paul/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from -e:1:in `<main>'
```

application.rb:8 is:

``` ruby
Bundler.require(*Rails.groups(assets: %w(development test))) # our Chef setup requires an assets group
```

**Comment by mooreniemi** [comment]
Also saw this issue, and @danrabinowitz's fix worked for me. Thanks, Dan.

**Comment by jgonera** [comment]
@grosser This is slightly off-topic, but can you tell us what you use instead or how your workflow changed?

**Comment by grosser** [comment]
no longer working on a giant rspec test suite / no longer need instant feedback when actual feedback is only 10s away :)

**Comment by grosser** [comment]
@danrabinowitz does it still work after adding that ... sounds like this would just completely disable it ?

**Comment by danrabinowitz** [comment]
Hmmm, it might be completely disabling it. I stopped using it, so I can't say.
