### ISSUE TITLE
Getting NameError: uninitialized  constant RSpec::Core::Formatters::ConsoleCodes after upgrade to 1.0.0

### ISSUE THREAD

**Issue by wojtha** [grosser/rspec-instafail#27]
Getting NameError: uninitialized  constant RSpec::Core::Formatters::ConsoleCodes after upgrade to 1.0.0. Downgrading back to 0.5.0 resolves the issue.

```
/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/notifications.rb:199:in `fully_formatted': uninitialized constant RSpec::Core::Formatters::ConsoleCodes (NameError)
    from /ruby/gems/2.3.0/gems/rspec-instafail-1.0.0/lib/rspec/instafail/rspec_3.rb:14:in `example_failed'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:189:in `block in notify'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `each'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:188:in `notify'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:140:in `example_failed'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:452:in `finish'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:410:in `fail_with_exception'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:550:in `block in run'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:591:in `each'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:591:in `for_filtered_examp
    les'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:550:in `rescue in run'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:556:in `run'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_s
    pecs'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_s
    pecs'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
    from /ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
    from /ruby/gems/2.3.0/gems/zeus-0.15.4/lib/zeus/rails.rb:216:in `test'
    from /ruby/gems/2.3.0/gems/zeus-0.15.4/lib/zeus.rb:148:in `block in command'
    from /ruby/gems/2.3.0/gems/zeus-0.15.4/lib/zeus.rb:135:in `fork'
    from /ruby/gems/2.3.0/gems/zeus-0.15.4/lib/zeus.rb:135:in `command'
    from /ruby/gems/2.3.0/gems/zeus-0.15.4/lib/zeus.rb:50:in `go'
    from -e:1:in `<main>'
```

**Comment by grosser** [comment]
try adding `--progress` to your .rspec and see if that fixes it :(

**Comment by wojtha** [comment]
Hmm, nope, getting `invalid option: --progress (defined in ./.rspec)` when set.

I am at RSpec 3.4.4.

my `.rspec` file look like this:

```
--color
--format RSpec::Instafail
--progress
```

**Comment by wojtha** [comment]
Oh. You probably mean this `--format progress`

With progress formatter in `.rspec` all operates normally.

```
--color
--format progress
```

I've also tried running just `rspec` outside the `zeus` preloader and it fails as well.

**Comment by grosser** [comment]
so with format progress zeus and non-zeus work, right ?

does adding a require for the missing module solve it too ?

**Comment by wojtha** [comment]
Cannot reproduce this anymore but have another issue

**Comment by hta-wtag** [comment]
thanks a lot for giving solution.

**Comment by anicholson** [comment]
I just hit this error (same message, same place) today.
